config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  devise_scope :user do
    root "users/sessions#new"
  end

  devise_for :users,  controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users, only: [:show]

  namespace :admin do
    resources :users, only: [:index, :destroy]
  end
  resources :expendable_items

  resources :about_app, only: [:index]

  post '/callback' => 'linebot#callback'

  authenticate :user do #authenticate
    mount Sidekiq::Web => '/sidekiq'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/expendable_item.rb
class ExpendableItem < ApplicationRecord
  validates :name, presence: true
  validates :amount_of_product, presence:true, numericality: {greater_than: 0}
  validates :amount_to_use, presence: true, numericality: {greater_than: 0}
  validates :frequency_of_use, presence: true, numericality: {greater_than: 0}
  validates :product_url, format: {with: /\A#{URI::regexp(['http', 'https'])}\z/}, unless: -> { product_url.blank? }
  enum auto_buy: {"する": true, "しない": false}
  validates :auto_buy, inclusion: {in: ["する", "しない"]}

  has_one_attached :image
  belongs_to :user

  paginates_per 6

  
end

app/controllers/expendable_items_controller.rb
class ExpendableItemsController < ApplicationController
  include ExpendableItemsHelper
  before_action :authenticate_user!
  before_action :correct_user_expendable_item, only: %i[show edit update destroy]

  def index
    @expendable_items = current_user.expendable_items.order('deadline_on ASC').page(params[:page])
  end

  def new
    @expendable_item = ExpendableItem.new
  end

  def create
    @expendable_item = ExpendableItem.new(expendable_item_params)
    @expendable_item.user_id = current_user.id
    @expendable_item.reference_date = Date.current
    deadline
    if @expendable_item.save
      flash[:notice] = '消耗品の新規登録が完了しました!'
      redirect_to expendable_items_path
    else
      render :new
    end
  end

  def show
    @expendable_item = ExpendableItem.find(params[:id])
    if params[:set_reference_day]
      reset_deadline
      flash[:notice] = '本日を消費開始日に再設定しました!'
      redirect_to expendable_items_path
    end
  end

  def edit
    @expendable_item = ExpendableItem.find(params[:id])
  end

  def update
    @expendable_item = ExpendableItem.find(params[:id])
    deadline
    if @expendable_item.update(expendable_item_params)
      flash[:notice] = '消耗品情報を更新しました!'
      redirect_to expendable_items_path
    else
      render :edit
    end
  end

  def destroy
    @expendable_item = ExpendableItem.find(params[:id])
    @expendable_item.destroy
    flash[:notice] = '消耗品情報を削除しました!'
    redirect_to expendable_items_path
  end

  private

  def expendable_item_params
    params.require(:expendable_item).permit(:name, :amount_of_product, :deadline_on, :image, :amount_to_use, :frequency_of_use, :product_url, :auto_buy)
  end
end

app/helpers/expendable_items_helper.rb
module ExpendableItemsHelper
  def reset_deadline
    reference_date = Date.current
    amount_of_day = @expendable_item.amount_of_product /  @expendable_item.amount_to_use / @expendable_item.frequency_of_use
    deadline_on = reference_date.since(amount_of_day.days)
    @expendable_item.update(deadline_on: deadline_on, reference_date: reference_date)
  end

  def deadline
    amount_of_product = params[:expendable_item][:amount_of_product].to_i
    amount_to_use = params[:expendable_item][:amount_to_use].to_i
    frequency_of_use = params[:expendable_item][:frequency_of_use].to_i
    if amount_of_product > 0 && amount_to_use > 0 && frequency_of_use > 0
      amount_of_day = amount_of_product /  amount_to_use / frequency_of_use
      @expendable_item.deadline_on = @expendable_item.reference_date.since(amount_of_day.days)
    end
  end

  def correct_user_expendable_item
    @expendable_item = ExpendableItem.find(params[:id])
    user = User.find(@expendable_item.user_id)
    return if user_admin?
    redirect_to expendable_items_path, flash: {warn: "アクセス権限がありません"} unless current_user?(user)
  end
end

app/views/expendable_items/_form.html.erb
<div class="image-bg">
  <div class="container mx-auto p-3">
    <div class="p-5 mx-auto my-10 block max-w-md bg-white border border-gray-200 rounded-lg shadow-md dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
      <%= form_with(model: expendable_item, local:true, class: "max-w-screen-md gap-4 mx-auto") do |form| %>
        <div>
          <%= form.label :name, t('.name'), class: "inline-block text-gray-800 text-sm sm:text-base mb-2 required" %>
          <%= form.text_field :name, class: "w-full bg-gray-50 text-gray-800 border focus:ring ring-indigo-300 rounded outline-none transition duration-100 px-3 py-2", placeholder: "商品名"%>
        </div>
        <div>
          <div>
            <%= form.label :amount_of_product, t('.amount_of_product'), class: "inline-block text-gray-800 text-sm sm:text-base mb-2 required" %>
            <%= form.text_field :amount_of_product, class: "w-full bg-gray-50 text-gray-800 border focus:ring ring-indigo-300 rounded outline-none transition duration-100 px-3 py-2", placeholder: "300" %>
          </div>
          <div>
            <%= form.label :amount_to_use, t('.amount_to_use'), class: "inline-block text-gray-800 text-sm sm:text-base mb-2 required"  %>
            <%= form.text_field :amount_to_use, class: "w-full bg-gray-50 text-gray-800 border focus:ring ring-indigo-300 rounded outline-none transition duration-100 px-3 py-2", placeholder: "3"  %>
          </div>
          <div>
            <p class="inline-block text-gray-800 text-sm sm:text-base mb-2 required"><%= form.label :frequency_of_use, t('.frequency_of_use') %>(1日に何回使用するか)</p>
            <%= form.text_field :frequency_of_use, class: "w-full bg-gray-50 text-gray-800 border focus:ring ring-indigo-300 rounded outline-none transition duration-100 px-3 py-2", placeholder: "1" %>
          </div>
        </div>
        <div>
          <%= form.label :image, t('.product_image'), class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
          <%= form.file_field :image, class: "block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" %>
        </div>
        <div>
          <div class="flex items-center w-full bg-gray-50 text-gray-800 border border-black focus:ring ring-indigo-300 rounded outline-none transition duration-100 my-4 px-3 py-2 dark:border-gray-700">
            <%= form.check_box :auto_buy, { class: "w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600" }, "する", "しない"  %>
            <%= form.label :auto_buy, t('.auto_buy'), class: "py-4 ml-2 w-full text-sm font-medium text-gray-800 dark:text-gray-300" %>
          </div>
          <div>
            <%= form.label :product_url, t('.product_url'), class: "inline-block text-gray-800 text-sm sm:text-base mb-2"  %>
            <%= form.url_field :product_url, class: "w-full bg-gray-50 text-gray-800 border focus:ring ring-indigo-300 rounded outline-none transition duration-100 px-3 py-2", placeholder: "https://example.com" %>
          </div>
        </div>
        <div class="text-lg md:text-2xl p-2 md:p-5 mx-auto mt-4 w-full text-center">
          <% if expendable_item.id == nil %>
            <%= form.submit t('.submit.create'), class: "m-3 bg-blue-200 hover:bg-blue-100 text-black py-2 px-4 rounded button-size" %>
          <% else %>
            <%= form.submit t('.submit.update'), class: "m-3 bg-green-200 hover:bg-green-100 text-black py-2 px-4 rounded button-size" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/expendable_items/edit.html.erb
<h1 class="md:text-8xl text-5xl place-content-center text-center ipad-h1"><%= @expendable_item.name %></h1>
<h1 class="md:text-8xl text-5xl place-content-center text-center border-b border-black ipad-h1"><%= t('.edit_item') %></h1>
<%= render 'form', expendable_item: @expendable_item %>

app/views/expendable_items/index.html.erb
<h1 class="md:text-8xl text-4xl place-content-center text-center mt-3 p-3 border-b border-black ipad-h1"><%= t('.shopping_index') %></h1>
<div class="image-bg min-h-screen">
  <div class="container mx-auto wrap p-3">
    <% @expendable_items.each do |item| %>
      <div class="wrap-raw mx-auto my-3 max-w-sm bg-white border border-gray-200 rounded-lg shadow-md dark:bg-gray-800 dark:border-gray-700">
        <% if item.image.present? %>
          <%= image_tag item.image.variant(resize_to_limit: [350, 350]), class: "rounded-t-lg w-full" %>
        <% else %>
          <%= image_tag 'no_image.jpg', size: '350x350', class: "rounded-t-lg w-full" %>
        <% end %>
        <div class="p-5">
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= t('.name') %></h5>
          <p class="text-center text-xl mb-3 font-normal text-gray-700 dark:text-gray-400"><%= item.name %></p>
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= t('.amount_of_product') %></h5>
          <p class="text-center text-xl mb-3 font-normal text-gray-700 dark:text-gray-400"><%= item.amount_of_product %></p>
          <div class="text-center text-xl mb-3 font-normal text-gray-700 dark:text-gray-400">
            <%= t('.to_') %>
            <strong class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
              <%=  (item.deadline_on - Time.zone.now).to_i / 1.day %>
            </strong>
            <%= t('.day') %>
          </div>
          <div class="text-lg md:text-xl m-2 flex justify-center whitespace-nowrap">
            <%= link_to t('.show'), expendable_item_path(item.id), class: "m-2 bg-gray-300 hover:bg-gray-200 font-semibold text-black py-2 px-2 rounded show-item"%>
            <%= link_to t('.delete'), expendable_item_path(item.id), method: :delete, data: { confirm: '本当に削除しますか?'}, class: "m-2 bg-gray-300 hover:bg-gray-200 font-semibold text-black py-2 px-2 rounded destroy-item" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate @expendable_items %>
</div>

app/views/expendable_items/new.html.erb
<h1 class="md:text-8xl text-4xl place-content-center text-center mt-4 p-4 border-b border-black ipad-h1"><%= t('.new_expendable_item') %></h1>
<%= render 'form', expendable_item: @expendable_item %>

app/views/expendable_items/show.html.erb
<h1 class="md:text-5xl text-3xl place-content-center p-5 text-center border-b border-black ipad-h1"><%= @expendable_item.name %><%= t('.show_item') %></h1>
<div class="image-bg">
  <div class="container mx-auto p-3">
    <div class="mx-auto my-10 block max-w-sm bg-white border border-gray-200 rounded-lg shadow-md dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
      <% if @expendable_item.image.present? %>
        <%= image_tag @expendable_item.image.variant(resize_to_limit: [350, 350]), class: "rounded-t-lg w-full" %>
      <% else %>
        <%= image_tag 'no_image.jpg', size: '350x350', class: "rounded-t-lg w-full" %>
      <% end %>
      <div class="p-5">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= t('.name') %></h5>
        <p class="text-center text-xl mb-3 font-normal text-gray-700 dark:text-gray-400"><%= @expendable_item.name %></p>
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= t('.amount_of_product') %></h5>
        <p class="text-center text-xl mb-3 font-normal text-gray-700 dark:text-gray-400"><%= @expendable_item.amount_of_product %></p>
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= t('.amount_to_use') %></h5>
        <p class="text-center text-xl mb-3 font-normal text-gray-700 dark:text-gray-400"><%= @expendable_item.amount_to_use %></p>
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= t('.frequency_of_use') %>(<%= t('.about_frequency') %>)</h5>
        <p class="text-center text-xl mb-3 font-normal text-gray-700 dark:text-gray-400"><%= @expendable_item.frequency_of_use %></p>
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= t('.auto_buy') %></h5>
        <p class="text-center text-xl mb-3 font-normal text-gray-700 dark:text-gray-400"><%= @expendable_item.auto_buy %></p>
        <div class="p-5 mx-auto mt-4 w-full text-center">
          <%= link_to t('.reset_reference_day'), expendable_item_path(@expendable_item.id, set_reference_day: true), data: { confirm: '再設定すると以前の消費開始日には戻せませんがよろしいですか?'}, class: "sm:m-2 bg-yellow-200 hover:bg-yellow-100 text-black py-2 px-2 rounded" %>
        </div>
        <div class="p-5 mx-auto mt-4 w-full text-center">
          <%= link_to t('.edit'), edit_expendable_item_path(@expendable_item.id), class: "sm:m-2 bg-green-200 hover:bg-green-100 text-black py-2 px-2 rounded" %>
          <%= link_to t('.delete'), expendable_item_path(@expendable_item.id), method: :delete, data: { confirm: '本当に削除しますか?'}, class: "sm:m-2 bg-red-200 hover:bg-red-100 text-black py-2 px-2 rounded" %>
        </div>
      </div>
    </div>
  </div>
</div>