config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  devise_scope :user do
    root "users/sessions#new"
  end

  devise_for :users,  controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users, only: [:show]

  namespace :admin do
    resources :users, only: [:index, :destroy]
  end
  resources :expendable_items

  resources :about_app, only: [:index]

  post '/callback' => 'linebot#callback'

  authenticate :user do #authenticate
    mount Sidekiq::Web => '/sidekiq'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  paginates_per 10

  before_destroy :not_destroy_no_admin

  has_many :expendable_items, dependent: :destroy

  validates :name, presence: true
  validates :ec_login_id, presence: true, unless: -> { ec_login_password.blank? }
  validates :ec_login_password, presence: true, unless: -> { ec_login_id.blank? }

  attr_encrypted :ec_login_id, key: 'This is a key that is 256 bits!!'
  attr_encrypted :ec_login_password, key: 'This is a key that is 256 bits!!'

  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable,
        :omniauthable, omniauth_providers: %i[line]

  def social_profile(provider)
    social_profiles.select { |sp| sp.provider == provider.to_s }.first
  end

  def set_values(omniauth)
    return if provider.to_s != omniauth["provider"].to_s || uid != omniauth["uid"]
    credentials = omniauth["credentials"]
    info = omniauth["info"]

    access_token = credentials["refresh_token"]
    access_secret = credentials["secret"]
    credentials = credentials.to_json
    name = info["name"]
  end

  def set_values_by_raw_info(raw_info)
    self.raw_info = raw_info.to_json
    self.save!
  end

  def remember_me
    false
  end

  def not_destroy_no_admin
    if User.where(admin: true).count == 1 && self.admin == true
      errors.add(:base, "管理者が0人になるため削除できません")
      throw :abort
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_required, only: [:index, :destroy]

  def index
    @users = User.order(:created_at).page(params[:page])
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy 
      flash[:notice] = "#{@user.name}を削除しました。"
      redirect_to admin_users_path
    else
      flash[:error] = '管理者が0人になってしまうため削除できません。'
      redirect_to admin_users_path
    end
  end

  private

  def admin_required
    redirect_to expendable_items_path, flash: {warn: "管理者以外はアクセスできません"} unless user_admin?
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #  super
  # end

  

  # DELETE /resource
  def destroy
    if current_user.destroy
      flash[:notice] = 'アカウントを削除しました。'
      redirect_to root_path
    else
      flash[:error] = '管理者が0人になってしまうため削除できません。'
      redirect_to user_path(current_user.id)
      end
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :line_alert, :ec_login_id, :ec_login_password])
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_update_path_for(resource)
    user_path(current_user.id)
  end
  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  prepend_before_action :require_no_authentication, only: :new
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

    #DELETE /resource/sign_out
  def destroy
    super
    flash[:notice] = 'ログアウトしました。'
  end

private

def require_no_authentication
  assert_is_devise_resource!
  return unless is_navigational_format?
  no_input = devise_mapping.no_input_strategies

  authenticated = if no_input.present?
    args = no_input.dup.push scope: resource_name
    warden.authenticate?(*args)
  else
    warden.authenticated?(resource_name)
  end

  if authenticated && resource = warden.user(resource_name)
    set_flash_message(:alert, 'already_authenticated', scope: 'devise.failure')
    redirect_to expendable_items_path
  end
end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:show]

  def show
    @user = User.find(params[:id])
  end

  private

  def correct_user
    @user = User.find(params[:id])
    redirect_to expendable_items_path, flash: {warn: "アクセス権限がありません"} unless current_user?(@user)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<h1 class="md:text-8xl text-4xl place-content-center text-center mt-3 p-3 border-b border-black ipad-h1">All Acount</h1>

<div class="image-bg md:min-h-screen">
  <div class="container mx-auto p-3">
    <div class="container mx-auto wrap p-3">
      <% @users.each do |user| %>
        <div class="p-3 h-full wrap-raw mx-auto my-3 max-w-sm bg-white border border-gray-200 rounded-lg shadow-md dark:bg-gray-800 dark:border-gray-700">
          <div class="p-5">
            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= t('.name') %></h5>
            <p class="text-center text-xl mb-3 font-normal text-gray-700 dark:text-gray-400"><%= user.name %></p>
            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= t('.expendable_items') %></h5>
            <p class="text-center text-xl mb-3 font-normal text-gray-700 dark:text-gray-400"><%= user.expendable_items.count %></p>
            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= t('.line_alert') %></h5>
            <p class="text-center text-xl mb-3 font-normal text-gray-700 dark:text-gray-400"><%= user.line_alert ? "ON" : "OFF" %></p>
            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= t('.connect_auto_buy') %></h5>
            <p class="text-center text-xl mb-3 font-normal text-gray-700 dark:text-gray-400"><%= user.ec_login_id.present? ? "あり" : "なし" %></p>
            <div class="text-lg md:text-xl m-2 flex justify-center whitespace-nowrap">
              <%= link_to t('.delete'), admin_user_path(user.id), method: :delete, data: {confirm: '本当に削除しますか？'}, class: "sm:m-1 bg-red-200 text-black py-2 px-1 rounded sm-admin md:text-2xl lg:text-4xl" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <%= paginate @users %>
  </div>
</div>