config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  devise_scope :user do
    root "users/sessions#new"
  end

  devise_for :users,  controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users, only: [:show]

  namespace :admin do
    resources :users, only: [:index, :destroy]
  end
  resources :expendable_items

  resources :about_app, only: [:index]

  post '/callback' => 'linebot#callback'

  authenticate :user do #authenticate
    mount Sidekiq::Web => '/sidekiq'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stock Roller</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('logo.png') %>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.5/dist/flowbite.min.css" />
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="min-h-screen flex flex-col">
    <header id="header">
      <div class="flex justify-center">
        <div class="logo none_sm">
          <% if user_signed_in? %>
            <%= link_to image_tag('logo.png', class: "logo-width"), expendable_items_path  %>
          <% else %>
            <%= link_to image_tag('logo.png', class: "logo-width"), new_user_session_path  %>
          <% end %>
        </div>
        <div class="logo none_md">
          <% if user_signed_in? %>
            <%= link_to image_tag('large_logo.jpg', class: "logo-width"), expendable_items_path  %>
          <% else %>
            <%= link_to image_tag('large_logo.jpg', class: "logo-width"), new_user_session_path  %>
          <% end %>
        </div>
      </div>
      <div class="hamburger">
        <span></span>
        <span></span>
        <span></span>
      </div>
      <nav class="globalMenuSp md-navi">
        <ul class="whitespace-nowrap">
          <% if user_signed_in? %>
            <% if user_admin? %>
              <li><%= link_to t('defaults.admin_page'), admin_users_path %></li>
            <% end %>
            <li><%= link_to t('defaults.shopping_memo'), expendable_items_path %></li>
            <li><%= link_to t('defaults.new_expendable_item'), new_expendable_item_path %></li>
            <li><%= link_to 'my account', user_path(current_user.id) %></li>
            <li><%= link_to t('defaults.add_line'), 'https://lin.ee/YTbl29b' %></li>
            <li><%= link_to 'Log out', destroy_user_session_path, class: 'dropdown-item', method: :delete %></li>
          <% else %>
            <li><%= link_to 'Welcome to Stock Roller', new_user_session_path, class: 'md:text-xs'%></li>
            <li><%= link_to t('defaults.about_app'), about_app_index_path %></li>
            <li><%= link_to t('defaults.add_line'), 'https://lin.ee/YTbl29b' %></li>
          <% end %>
        </ul>
      </nav>
    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key} hidden") %>
    <% end %>
    <main id="main">
      <%= yield %>
    </main>
    <div class="flex justify-center mb-5 p-10 text-xl border-t border-b border-black mt-auto">
      <p class="text-sm md:text-lg">Product By Tomoki Matsubuchi</p>
    </div>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script src="https://unpkg.com/flowbite@1.5.5/dist/flowbite.js"></script>
    <script>
      AOS.init();
    </script>
  </body>
</html>